FinalProject.pdf: FinalProject.tex background.tex problem.tex code.tex paperstyle.tex solution.tex preparation.tex
	pdflatex FinalProject.tex
	pdflatex FinalProject.tex

clean:
	rm *.aux *.out *.toc *.lof *.log

clear:
	rm *.aux *.out *.toc *.lof *.log FinalProject.pdf
